### Test FastAPI Root Endpoint
GET http://127.0.0.1:8000/

### Get API Docs
GET http://127.0.0.1:8000/docs

### Example of a POST Request
### Fetch and Clone a GitHub Repository
POST http://127.0.0.1:8000/fetch-repo
Content-Type: application/json

{
  "repo_url": "https://github.com/SYYFT/repo_ai.git"
}

### Parse the Repository
GET http://127.0.0.1:8000/parse/repo_ai

### Get Parsed Data
GET http://127.0.0.1:8000/get_parsed_data
